// <auto-generated />
using System;
using DispatcherApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DispatcherApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DispatcherDbContext))]
    [Migration("20260911211630_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DispatcherApp.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.BuildingSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ConstructionObjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionObjectId");

                    b.ToTable("building_sections", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.CapacityOverride", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CapacityUnits")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("LineCapabilityId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("LineCapabilityId", "Date")
                        .IsUnique();

                    b.ToTable("capacity_overrides", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.Carrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("carriers", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.ConstructionObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("construction_objects", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.ConstructionTakt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("ConstructionObjectId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateOnly>("PlannedProductionEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PlannedProductionStartDate")
                        .HasColumnType("date");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionObjectId");

                    b.ToTable("construction_takts", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.Demand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CurrentRevisionId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRevisionId")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("demands", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.DemandRevision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("ConstructionTaktId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("DemandId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("EarliestDeliveryDate")
                        .HasColumnType("date");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("integer");

                    b.Property<int>("PriorityOrder")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("RequiredDeliveryDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("RequiredProductionEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("RequiredProductionStartDate")
                        .HasColumnType("date");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionTaktId");

                    b.HasIndex("DemandId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("demand_revisions", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingSectionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingSectionId");

                    b.ToTable("floors", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.LineCapability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DefaultDailyCapacityUnits")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionLineId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("ProductionLineId", "ProductTypeId")
                        .IsUnique();

                    b.ToTable("line_capabilities", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("plants", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("CladdingWidthWithBendsMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("CorniceWidthIncreaseMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HeightMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("LeftBendMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RightBendMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("ThicknessIncreaseMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("ThicknessMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("TotalWidthWithCorniceMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("WidthMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.HasIndex("ProductTypeId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.ProductAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BuildingSectionId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("ConstructionObjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("FloorId")
                        .HasColumnType("integer");

                    b.Property<string>("InstallationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuildingSectionId");

                    b.HasIndex("ConstructionObjectId");

                    b.HasIndex("FloorId");

                    b.HasIndex("ProductId");

                    b.ToTable("product_assignments", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.ProductIdentifier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("Type", "Value")
                        .IsUnique();

                    b.ToTable("product_identifiers", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("product_types", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.ProductionAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AssignmentMethod")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DecisionSnapshotJson")
                        .HasColumnType("jsonb");

                    b.Property<long>("DemandRevisionId")
                        .HasColumnType("bigint");

                    b.Property<string>("OverrideReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly>("PlannedProductionDate")
                        .HasColumnType("date");

                    b.Property<int>("ProductionLineId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Score")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DemandRevisionId");

                    b.HasIndex("ProductionLineId");

                    b.ToTable("production_assignments", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.ProductionLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("production_lines", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.ProjectPosition", b =>
                {
                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int?>("BuildingSectionId")
                        .HasColumnType("integer");

                    b.Property<int>("ConstructionObjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("FloorId")
                        .HasColumnType("integer");

                    b.Property<string>("InstallationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("ProductId");

                    b.HasIndex("BuildingSectionId");

                    b.HasIndex("ConstructionObjectId");

                    b.HasIndex("FloorId");

                    b.ToTable("project_positions", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.StorageArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacityUnits")
                        .HasColumnType("integer");

                    b.Property<int?>("ConstructionObjectId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("PlantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionObjectId");

                    b.HasIndex("PlantId");

                    b.ToTable("storage_areas", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.StoragePlacement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ArrivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("DepartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("StorageAreaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StorageAreaId");

                    b.ToTable("storage_placements", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.TaktAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("ConstructionTaktId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionTaktId");

                    b.HasIndex("ProductId");

                    b.ToTable("takt_assignments", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.TransportRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConstructionObjectId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("DistanceKm")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int?>("EstimatedTravelMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TurnoverCoefficientPerDay")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionObjectId");

                    b.HasIndex("PlantId", "ConstructionObjectId")
                        .IsUnique();

                    b.ToTable("transport_routes", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.Trip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ActualArrivalAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ActualDepartureAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ActualLoadingAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("ConstructionObjectId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PlannedArrivalAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PlannedDepartureAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PlannedLoadingAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TripNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("UnloadingPointId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionObjectId");

                    b.HasIndex("PlantId");

                    b.HasIndex("TripNumber")
                        .IsUnique();

                    b.HasIndex("UnloadingPointId");

                    b.HasIndex("VehicleId");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.TripItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AddedByUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("LoadingSequence")
                        .HasColumnType("integer");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TripId", "ProductId")
                        .IsUnique();

                    b.ToTable("trip_items", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.UnloadingPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConstructionObjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionObjectId");

                    b.ToTable("unloading_points", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.Vehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CarrierId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AllowedRightLeftImbalanceKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal?>("CargoVolumeM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int>("LoadingPlatformCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("LoadingPlatformLengthMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal?>("LoadingPlatformWidthMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal?>("MaxCargoHeightMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal?>("MaxPayloadKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal?>("MinPayloadKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RollingStockType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal?>("TotalTrainLengthMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal?>("TurningRadiusMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("Id");

                    b.ToTable("vehicle_types", (string)null);
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.BuildingSection", b =>
                {
                    b.HasOne("DispatcherApp.Domain.Entities.ConstructionObject", "ConstructionObject")
                        .WithMany("Sections")
                        .HasForeignKey("ConstructionObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConstructionObject");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.CapacityOverride", b =>
                {
                    b.HasOne("DispatcherApp.Domain.Entities.LineCapability", "LineCapability")
                        .WithMany("CapacityOverrides")
                        .HasForeignKey("LineCapabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LineCapability");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.ConstructionTakt", b =>
                {
                    b.HasOne("DispatcherApp.Domain.Entities.ConstructionObject", "ConstructionObject")
                        .WithMany()
                        .HasForeignKey("ConstructionObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConstructionObject");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.Demand", b =>
                {
                    b.HasOne("DispatcherApp.Domain.Entities.DemandRevision", "CurrentRevision")
                        .WithOne()
                        .HasForeignKey("DispatcherApp.Domain.Entities.Demand", "CurrentRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DispatcherApp.Domain.Entities.Product", "Product")
                        .WithMany("Demands")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentRevision");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.DemandRevision", b =>
                {
                    b.HasOne("DispatcherApp.Domain.Entities.ConstructionTakt", "ConstructionTakt")
                        .WithMany("DemandRevisions")
                        .HasForeignKey("ConstructionTaktId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DispatcherApp.Domain.Entities.Demand", "Demand")
                        .WithMany("Revisions")
                        .HasForeignKey("DemandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConstructionTakt");

                    b.Navigation("Demand");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.Floor", b =>
                {
                    b.HasOne("DispatcherApp.Domain.Entities.BuildingSection", "BuildingSection")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BuildingSection");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.LineCapability", b =>
                {
                    b.HasOne("DispatcherApp.Domain.Entities.ProductType", "ProductType")
                        .WithMany("LineCapabilities")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DispatcherApp.Domain.Entities.ProductionLine", "ProductionLine")
                        .WithMany("Capabilities")
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductType");

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.Product", b =>
                {
                    b.HasOne("DispatcherApp.Domain.Entities.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.ProductAssignment", b =>
                {
                    b.HasOne("DispatcherApp.Domain.Entities.BuildingSection", "BuildingSection")
                        .WithMany()
                        .HasForeignKey("BuildingSectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DispatcherApp.Domain.Entities.ConstructionObject", "ConstructionObject")
                        .WithMany("ProductAssignments")
                        .HasForeignKey("ConstructionObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DispatcherApp.Domain.Entities.Floor", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DispatcherApp.Domain.Entities.Product", "Product")
                        .WithMany("Assignments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BuildingSection");

                    b.Navigation("ConstructionObject");

                    b.Navigation("Floor");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.ProductIdentifier", b =>
                {
                    b.HasOne("DispatcherApp.Domain.Entities.Product", "Product")
                        .WithMany("Identifiers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.ProductionAssignment", b =>
                {
                    b.HasOne("DispatcherApp.Domain.Entities.DemandRevision", "DemandRevision")
                        .WithMany("ProductionAssignments")
                        .HasForeignKey("DemandRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DispatcherApp.Domain.Entities.ProductionLine", "ProductionLine")
                        .WithMany("ProductionAssignments")
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DemandRevision");

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.ProductionLine", b =>
                {
                    b.HasOne("DispatcherApp.Domain.Entities.Plant", "Plant")
                        .WithMany("ProductionLines")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.ProjectPosition", b =>
                {
                    b.HasOne("DispatcherApp.Domain.Entities.BuildingSection", "BuildingSection")
                        .WithMany()
                        .HasForeignKey("BuildingSectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DispatcherApp.Domain.Entities.ConstructionObject", "ConstructionObject")
                        .WithMany("ProjectPositions")
                        .HasForeignKey("ConstructionObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DispatcherApp.Domain.Entities.Floor", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DispatcherApp.Domain.Entities.Product", "Product")
                        .WithOne("ProjectPosition")
                        .HasForeignKey("DispatcherApp.Domain.Entities.ProjectPosition", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BuildingSection");

                    b.Navigation("ConstructionObject");

                    b.Navigation("Floor");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.StorageArea", b =>
                {
                    b.HasOne("DispatcherApp.Domain.Entities.ConstructionObject", "ConstructionObject")
                        .WithMany("StorageAreas")
                        .HasForeignKey("ConstructionObjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DispatcherApp.Domain.Entities.Plant", "Plant")
                        .WithMany("StorageAreas")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ConstructionObject");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.StoragePlacement", b =>
                {
                    b.HasOne("DispatcherApp.Domain.Entities.Product", "Product")
                        .WithMany("StoragePlacements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DispatcherApp.Domain.Entities.StorageArea", "StorageArea")
                        .WithMany("Placements")
                        .HasForeignKey("StorageAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StorageArea");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.TaktAssignment", b =>
                {
                    b.HasOne("DispatcherApp.Domain.Entities.ConstructionTakt", "ConstructionTakt")
                        .WithMany("TaktAssignments")
                        .HasForeignKey("ConstructionTaktId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DispatcherApp.Domain.Entities.Product", "Product")
                        .WithMany("TaktAssignments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConstructionTakt");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.TransportRoute", b =>
                {
                    b.HasOne("DispatcherApp.Domain.Entities.ConstructionObject", "ConstructionObject")
                        .WithMany()
                        .HasForeignKey("ConstructionObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DispatcherApp.Domain.Entities.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConstructionObject");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.Trip", b =>
                {
                    b.HasOne("DispatcherApp.Domain.Entities.ConstructionObject", "ConstructionObject")
                        .WithMany()
                        .HasForeignKey("ConstructionObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DispatcherApp.Domain.Entities.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DispatcherApp.Domain.Entities.UnloadingPoint", "UnloadingPoint")
                        .WithMany("Trips")
                        .HasForeignKey("UnloadingPointId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DispatcherApp.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Trips")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConstructionObject");

                    b.Navigation("Plant");

                    b.Navigation("UnloadingPoint");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.TripItem", b =>
                {
                    b.HasOne("DispatcherApp.Domain.Entities.Product", "Product")
                        .WithMany("TripItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DispatcherApp.Domain.Entities.Trip", "Trip")
                        .WithMany("Items")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.UnloadingPoint", b =>
                {
                    b.HasOne("DispatcherApp.Domain.Entities.ConstructionObject", "ConstructionObject")
                        .WithMany()
                        .HasForeignKey("ConstructionObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConstructionObject");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("DispatcherApp.Domain.Entities.Carrier", "Carrier")
                        .WithMany("Vehicles")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DispatcherApp.Domain.Entities.VehicleType", "VehicleType")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrier");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.BuildingSection", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.Carrier", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.ConstructionObject", b =>
                {
                    b.Navigation("ProductAssignments");

                    b.Navigation("ProjectPositions");

                    b.Navigation("Sections");

                    b.Navigation("StorageAreas");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.ConstructionTakt", b =>
                {
                    b.Navigation("DemandRevisions");

                    b.Navigation("TaktAssignments");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.Demand", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.DemandRevision", b =>
                {
                    b.Navigation("ProductionAssignments");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.LineCapability", b =>
                {
                    b.Navigation("CapacityOverrides");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.Plant", b =>
                {
                    b.Navigation("ProductionLines");

                    b.Navigation("StorageAreas");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.Product", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Demands");

                    b.Navigation("Identifiers");

                    b.Navigation("ProjectPosition");

                    b.Navigation("StoragePlacements");

                    b.Navigation("TaktAssignments");

                    b.Navigation("TripItems");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.ProductType", b =>
                {
                    b.Navigation("LineCapabilities");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.ProductionLine", b =>
                {
                    b.Navigation("Capabilities");

                    b.Navigation("ProductionAssignments");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.StorageArea", b =>
                {
                    b.Navigation("Placements");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.Trip", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.UnloadingPoint", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("DispatcherApp.Domain.Entities.VehicleType", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
